"""TrackedDetection — inter-service contract from tracking to storage/alerting.

Produced by: services/tracking
Consumed by: services/storage, services/alerting
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from .detection import BoundingBox, PlateCandidate
from .inference import AttributePredictions


class ConfidenceSummary(BaseModel):
    """Rolled-up confidence scores across the track lifetime."""

    best_plate_confidence: Optional[float] = Field(None, ge=0.0, le=1.0)
    ocr_candidate_count: int = Field(0, ge=0, description="Number of OCR reads accumulated")
    frames_tracked: int = Field(0, ge=0, description="Total frames this track was active")
    first_seen_utc: Optional[str] = None
    last_seen_utc: Optional[str] = None


class EvidenceRefs(BaseModel):
    """Local filesystem paths to evidence media for this tracked detection."""

    best_frame_path: Optional[str] = Field(None, description="Best-quality full frame for this track")
    best_plate_crop_path: Optional[str] = Field(None, description="Best plate crop across all frames")
    snippet_path: Optional[str] = Field(None, description="Short video snippet covering the track")


class TrackedDetection(BaseModel):
    """A fully resolved, tracker-fused detection ready for storage and alerting.

    This is the output of the tracking service after aggregating OCR candidates,
    promoting the best plate read, and suppressing duplicates.
    """

    detection_id: str = Field(..., description="Stable unique detection identifier (generated by tracking)")
    tracker_id: str = Field(..., description="Tracker identity string for this vehicle track")
    camera_id: str = Field(..., description="Source camera identifier")
    timestamp_utc: str = Field(..., description="Timestamp of the best or final frame (ISO 8601 UTC)")

    best_plate_candidate: Optional[PlateCandidate] = Field(
        None, description="Promoted best OCR read for this track"
    )
    alternate_plate_candidates: list[PlateCandidate] = Field(
        default_factory=list, description="Other OCR candidates not promoted as best"
    )

    vehicle_bbox: BoundingBox = Field(..., description="Vehicle bbox from the best frame")
    plate_bbox: Optional[BoundingBox] = Field(None, description="Plate bbox from the best frame")

    vehicle_attributes: Optional[AttributePredictions] = Field(
        None, description="Best attribute predictions for this track"
    )

    evidence_refs: EvidenceRefs = Field(default_factory=EvidenceRefs)
    confidence_summary: ConfidenceSummary = Field(default_factory=ConfidenceSummary)
    frame_number: int = Field(..., ge=0, description="Frame number of the best detection frame")
